pp 3914 extract container mass
autoprotocol/autoprotocol-python pull request #305
Opened 2021-06-22 00:15 UTC by joshhacksthings

2021-06-22 00:27 UTC, HugoMayoral submitted a review, later dismissed
LGTM!

2021-06-22 21:18 UTC, xiliuStrateos requested changes
nit - doc str change

2021-06-22 21:18 UTC, xiliuStrateos commented on autoprotocol/container.py
> +        ValueError
This method does not raise `ValueError`

2021-06-22 21:18 UTC, xiliuStrateos commented on autoprotocol/container.py
> +            Theoretical volume to indicate for a Well.
volume or mass?

2021-06-23 16:48 UTC, xiliuStrateos approved these changes

2021-06-23 22:15 UTC, merged