Stdv 1126 corning 4513 container type
autoprotocol/autoprotocol-python pull request #343
Opened 2022-01-07 00:34 UTC by ericschade

Adding the Corning 4513 container type to APPy.

2022-01-07 00:38 UTC, ericschade commented
cleaned up commit history with force push

2022-01-07 01:27 UTC, ericschade commented on autoprotocol/container_type.py
> +    well_coating="Corning NBS(nonbinding surface)",
im pretty sure this can be anything - i just went to the vendor site and transcribed from there

2022-01-10 23:34 UTC, joshhacksthings requested changes
almost there:

- [x] remove capitalized letter in dash-case shortname
- [ ] Check for other existing NBS coatings, would suggest conforming to any existing string that has NBS in it already

2022-01-10 23:34 UTC, joshhacksthings commented on autoprotocol/container_type.py
> +    "384-Corning-4513-round-lv": ROUND384LV,
no capitals in dash-case pls!

2022-01-10 23:34 UTC, joshhacksthings commented on autoprotocol/container_type.py
> +    shortname="384-Corning-4513-round-lv",
update here once uncapitalized below

2022-01-11 17:16 UTC, ericschade commented
> almost there:
> 
> * [x]  remove capitalized letter in dash-case shortname
> * [ ]  Check for other existing NBS coatings, would suggest conforming to any existing string that has NBS in it already

I don't see any other examples of NBS in the description of plates. do you think that it should be described differently than it is here?

2022-01-11 20:28 UTC, joshhacksthings approved these changes
lgtm

2022-01-11 20:30 UTC, merged